//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMODULELINK_H
#define UIMENUWNDWIFIMODULELINK_H

#include "UIFramework.h"
extern void FlowMovie_Icon_WIFILink_DrawPIM(BOOL bDraw);
extern void FlowMovieWifi_IconDrawRecTime(VControl *pCtrl);
extern void FlowMovie_Icon_WIFILink_DrawDateTime(void);
extern void FlowMovieWifi_IconDrawMaxRecTime(VControl *pCtrl);
extern void FlowMovieWifi_IconHideMaxRecTime(VControl *pCtrl);
extern void FlowWiFiMovie_StartRec(void);
extern void FlowWiFiMovie_StopRec(void);
extern  void LED_BLUE_TurnOff(void);
extern  void LED_RED_TurnOn(void);

extern VControl UIMenuWndWiFiModuleLinkCtrl;//Panel type 

extern VControl UIMenuWndWiFiModuleLink_StaticICN_WiFiCtrl;//Static type 

extern VControl UIMenuWndWiFiModuleLink_StatusTXT_WiFiModeCtrl;//Status type 

typedef enum {
	UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_STRID_WIFI_AP_MODE,
	UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_STRID_WIFI_CLIENT_MODE,
	UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_MAX
} UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_Setting;

extern VControl UIMenuWndWiFiModuleLink_StaticTXT_SSIDCtrl;//Static type 

extern VControl UIMenuWndWiFiModuleLink_StaticTXT_KeyCtrl;//Static type 

extern VControl UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOffCtrl;//Tab type 

typedef enum {
	UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_Button_Refresh,
	UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_Button_WiFiOff,
	UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_MAX
} UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_Setting;

extern VControl Button_RefreshCtrl;//Button type 

extern VControl Button_WiFiOffCtrl;//Button type 

extern VControl UIMenuWndWiFiModuleLink_PanelCtrl;//Panel type

extern VControl UIMenuWndWiFiModuleLink_Static_timeCtrl;//Static type

extern VControl UIMenuWndWiFiModuleLink_Static_maxtimeCtrl;//Static type

extern VControl UIMenuWndWiFiModuleLink_Status_LOCKCtrl;
extern VControl UIMenuWndWiFiModuleLink_StaticIcon_PIMCCtrl;//Static type //xiao160927

typedef enum
{
UIMenuWndWiFiModuleLink_LOCK_ICONID_NULL,
UIMenuWndWiFiModuleLink_LOCK_ICON_LOCK,
UIMenuWndWiFiModuleLink_Status_LOCK_MAX
}UIMenuWndWiFiModuleLink_Status_LOCK_Setting;

extern VControl UIMenuWndWiFiModuleLink_YMD_StaticCtrl;//Static type

extern VControl UIMenuWndWiFiModuleLink_HMS_StaticCtrl;//Static type

//---------------------UIMenuWndWiFiModuleLinkCtrl User Export---------------------------
#endif
