//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMOBILELINKOK_H
#define UIMENUWNDWIFIMOBILELINKOK_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiMobileLinkOKCtrl;//Panel type

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl;//Static type

extern VControl UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl;//Button type

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl;//Static type

extern VControl UIMenuWndWiFiMobileLinkOK_PanelCtrl;//Panel type

extern VControl UIMenuWndWiFiModuleLinkOK_StaticIcon_PIMCCtrl;//Static type

extern VControl UIMenuWndWiFiMobileLinkOK_Static_timeCtrl;//Static type

extern VControl UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl;//Static type

extern VControl UIMenuWndWiFiModuleLinkOK_YMD_StaticCtrl;//Static type

extern VControl UIMenuWndWiFiModuleLinkOK_HMS_StaticCtrl;//Static type
extern VControl UIMenuWndWiFiModuleLinkOK_Status_LOCKCtrl;
typedef enum
{
UIMenuWndWiFiModuleLinkOK_LOCK_ICONID_NULL,
UIMenuWndWiFiModuleLinkOK_LOCK_ICON_LOCK,
UIMenuWndWiFiModuleLinkOK_Status_LOCK_MAX
}UIMenuWndWiFiModuleLinkOK_Status_LOCK_Setting;

//---------------------UIMenuWndWiFiMobileLinkOKCtrl User Export---------------------------
#endif
