//This source code is generated by UI Designer Studio.

#include "stdio.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileLinkOKRes.c"
#include "WifiAppCmd.h"
#include "UIFlow.h"
#include "UIAppNetwork.h"
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
#include "ImageApp_UsbMovie.h"
#include "ImageUnit_UsbUVAC.h"
#include "UsbCmdAPI.h"
#endif
//#NT#2016/05/31#Ben Wang -end
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG        1

#if (_UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Global Variables -----------------------------
static UINT32  gUIMenuWndWiFiOkDataTimerID = NULL_TIMER;
extern void LED_RED_TurnOn(void);
extern void LED_RED_TurnOff(void);
extern void LED_BLUE_TurnOn(void);
extern void LED_BLUE_TurnOff(void);


UINT32 bWaitMoiveVedioReady= FALSE;
extern void FlowMovieWifi_IconDrawRecTime(VControl *pCtrl);
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK)
//CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkSts)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
//CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLinkOK_Status_LOCK)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_time)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLinkOK_YMD_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLinkOK_HMS_Static)
CTRL_LIST_END
char StringTmpBuf[32] = {0};
//----------------------UIMenuWndWiFiMobileLinkOKCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeChangeModeDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndWiFiMobileLinkOK_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndWiFiMobileLinkOK_OnClose)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK, UIMenuWndWiFiMobileLinkOK_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_DHCP_REQ, UIMenuWndWiFiMobileLinkOK_DHCP_REQ)

EVENT_ITEM(NVTEVT_STORAGE_INIT, UIMenuWndWiFiModuleLinkOK_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIMenuWndWiFiModuleLinkOK_OnStorageChange)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE, UIMenuWndWiFiMobileLinkOK_OnBackgroundDone)
EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME, UIMenuWndWiFiMobileLinkOK_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR, UIMenuWndWiFiMobileLinkOK_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW, UIMenuWndWiFiMobileLinkOK_OnStorageSlow)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC, UIMenuWndWiFiMobileLinkOK_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_RAWENC_OK, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB)
EVENT_ITEM(NVTEVT_CB_RAWENC_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_WRITE_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_DCF_FULL, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIMenuWndWiFiMobileLinkOK_OnBatteryLow)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED, UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated)
EVENT_ITEM(NVTEVT_CB_MOVIE_VEDIO_READY, UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady)
EVENT_ITEM(NVTEVT_TIMER, UIMenuWndWiFiMobileLinkOK_OnTimer)
EVENT_END

BOOL  WIFI_LINKOK_Gsensor_Rec = FALSE;
extern char gLastMacAddr[];
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	static char Buf1[32] = {0}, buf2[32] = {0} ;

	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, 0);
	Input_SetKeyMask(KEY_CONTINUE, 0);
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, IMGUNIT_UVAC_CFG_CDC_ENABLE)) {
			MEM_RANGE WorkBuf;
			WorkBuf.Addr = OS_GetMempoolAddr(POOL_ID_USBCMD);
			WorkBuf.Size = POOL_SIZE_USBCMD;
			UsbCmd_Open(&WorkBuf);
		}
		snprintf(Buf1, sizeof(Buf1), "UVC Connected");
		//just don't show this string
		StringTmpBuf[0] = 0;
	} else
#endif
	{
	  WIFI_LINKOK_Gsensor_Rec = TRUE;
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
		snprintf(Buf1, sizeof(Buf1), "WiFi Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
#else
		snprintf(Buf1, sizeof(Buf1), "Ethernet Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " IP : %s", UINet_GetIP());
#endif
	}
//#NT#2016/05/31#Ben Wang -end
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl, STATIC_VALUE, Txt_Pointer(Buf1));
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));

	snprintf(buf2, sizeof(buf2), "Press Select to Disconnect");
	UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl, 0, BTNITM_STRID, Txt_Pointer(buf2));


	if (gUIMenuWndWiFiOkDataTimerID==NULL_TIMER)
    {
        ;// gUIMenuWndWiFiOkDataTimerID= GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_01SEC_TIMER, CONTINUE);
    }
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) != SYS_SUBMODE_UVC)
#endif
	{
		//make sure, connec to RTSP mode
		if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
			Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
		}
	}
//#NT#2016/05/31#Ben Wang -end
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStart();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStart();
	//refress iocn
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,0);
	FlowMovieWifi_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl)	;

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
BOOL LINKOK_OPEN_SSID = FALSE;
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (UI_GetData(FL_MOVIE_SIZE_MENU) != UI_GetData(FL_MOVIE_SIZE)) {
		Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, UI_GetData(FL_MOVIE_SIZE_MENU));
	}
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStop();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStop();
        if (gUIMenuWndWiFiOkDataTimerID != NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIMenuWndWiFiOkDataTimerID);
    }

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	//if(System_GetState(SYS_STATE_CURRSUBMODE)==SYS_SUBMODE_UVC && System_GetState(SYS_STATE_NEXTSUBMODE)!=SYS_SUBMODE_UVC)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, IMGUNIT_UVAC_CFG_CDC_ENABLE)) {
			UsbCmd_Close();
		}
	}
#endif
//#NT#2016/05/31#Ben Wang -end
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,0);
	FlowMovieWifi_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl)	;

	LINKOK_OPEN_SSID = TRUE;
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 bNewUser = 0 ;
	if (paramNum) {
		bNewUser = paramArray[0];
	}
#if 0  //print MAC when client get IP
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#endif
	if (bNewUser) {
		//delay 500 ms,disconnect last user and
		//in window,use GxTimer replace Timer Delay,it would occupat UI task
		GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DISCONNECT_LAST_TIMER, ONE_SHOT);
	}

#if 0 // Moved to UINet_DhcpSrvCBCliConn.
	//make sure, connec to RTSP mode
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}
#endif

	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	char *pMAC = 0;
	if (paramNum) {
		pMAC = (char *)paramArray[0];
	}
	//#NT#2016/12/27#YongChang Qui -begin
	//#NT#don't display mac address on UI if mac is 0:0:0:0:0:0:0
	if (pMAC && (pMAC[0] || pMAC[1] || pMAC[2] || pMAC[3] || pMAC[4] || pMAC[5]))
		//#NT#2016/12/27#YongChang Qui -end
	{
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %02x%02x%02x%02x%02x%02x", pMAC[0], pMAC[1], pMAC[2]\
				 , pMAC[3], pMAC[4], pMAC[5]);
		UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
        UISound_Play(DEMOSOUND_SOUND_CHECK_CARD_TONE);
		UIMenuWndWiFiMobileLinkOKTraceMsg("card err,removed\r\n");
	} else {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card insert\r\n");
		if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
		} else {
			ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_REOPEN, 0);
		}				UISound_Play(DEMOSOUND_SOUND_CHECK_CARD_TONE);

		WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_INSERT);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	UIMenuWndWiFiMobileLinkOKTraceMsg("card removed\r\n");
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_PLAYBACK) {
		ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_CLOSE, 0);
	}
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_REMOVE);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	NVTEVT event;
	UINT32 status;

	event = paramArray[ONDONE_PARAM_INDEX_CMD];
	status = paramArray[ONDONE_PARAM_INDEX_RET];
	debug_err(("%s event = 0x%x, status=%d\r\n", __FUNCTION__, event, status));

	switch (event) {
	case NVTEVT_BKW_FORMAT_CARD: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FORMAT_NAND: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FW_UPDATE: {
			if (status) {
				debug_err(("%s:update FW fail %d\r\n", __FUNCTION__, status));
				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, status + WIFIAPP_RET_FW_OFFSET);
			} else {
				//#NT#2016/03/23#Isiah Chang -begin
				//#NT#add new Wi-Fi UI flow.
				INT32 ret;

				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, WIFIAPP_RET_OK);

				ret = FileSys_DeleteFile(FW_UPDATE_NAME);
				if (ret != FST_STA_OK) {
					debug_err(("%s:delete FW fail %d\r\n", __FUNCTION__, status));
				}
				//#NT#2016/03/23#Isiah Chang -end
				Delay_DelayMs(2000);
				// Should power off immediatelly
				System_PowerOff(SYS_POWEROFF_NORMAL);
			}
			break;
		}

	default:
		debug_err(("%s:Unknown event 0x%x\r\n", __FUNCTION__, event));
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Full");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));
	return WiFiCmd_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Error");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Slow Card");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnStorageSlow(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{	if (System_GetState(SYS_STATE_CARD)  != CARD_REMOVED)
	{
		if (WiFiCmd_GetStatus()==WIFI_MOV_ST_RECORD && paramNum)
		{
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,!UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl));
			FlowMovieWifi_IconHideMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
			FlowMovieWifi_IconDrawRecTime(&UIMenuWndWiFiMobileLinkOK_Static_timeCtrl);
		}
		else
		{
                CHKPNT;
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,0);
			FlowMovieWifi_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
		}
    }
	return WiFiCmd_OnMovieOneSec(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncJpgOKCB(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncErr(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n", __FUNCTION__);

	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Battery Low");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_BATTERY_LOW);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
#else
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), "No connect");
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	UINet_CliReConnect(1);
#endif
#endif
//#NT#2016/03/23#Isiah Chang -end
	return NVTEVT_CONSUME;

	//Ux_CloseWindow(pCtrl,0);

	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnExeMovieVedioReady(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;
	uiEvent = paramNum ? paramArray[0] : 0;

	switch (uiEvent) {
	case NVTEVT_DISCONNECT_LAST_TIMER:
		UINet_AddACLTable();
		return NVTEVT_CONSUME;
    case NVTEVT_01SEC_TIMER:
        		FlowMovie_OnTimer1SecIndex();
			return NVTEVT_CONSUME;

	case NVTEVT_DELAY_CLOSE_TIMER: {
			//#NT#2016/03/08#Niven Cho -begin
			//#NT#because it is long time closing the linux-wifi, we don't change mode to movie video ahead.
			//#NT#use Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0),not post event
#if (WIFI_FUNC == ENABLE)
				INT32 curMode = System_GetState(SYS_STATE_CURRMODE);
				if ( curMode!= PRIMARY_MODE_MOVIE) {
			    	Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					Ux_CloseWindow(&UIFlowWndMovieCtrl,0);
			    	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, curMode,SYS_SUBMODE_NORMAL);
				} else {
					VControl *pWnd =0 ;
					Ux_GetWindowByIndex(&pWnd, 1);

					Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					System_ChangeSubMode(SYS_SUBMODE_NORMAL);
					Ux_CloseWindow(pWnd, 0);
				}
#endif
			//#NT#2016/03/08#Niven Cho -end
			return NVTEVT_CONSUME;
		}

//#NT#2017/01/03#Isiah Chang -begin
//#NT#Add WiFiCmd Bitrate control.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	case NVTEVT_1SEC_TIMER: {
			WiFiCmd_HBOneSec();
			return NVTEVT_CONSUME;
		}
#endif
//#NT#2017/01/03#Isiah Chang -end
	//case NVTEVT_05SEC_TIMER: {
			//WiFiCmd_OnMotionDetect();
			//return NVTEVT_CONSUME;
		//}
	default:
		return NVTEVT_CONSUME;
	}
}



//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkSts)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_TakePIC(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Tab_REC(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Button_REC_RAWEN(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
//EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndWiFiMobileLinkOK_Button_Disconnect_TakePIC)
//EVENT_ITEM(NVTEVT_KEY_CUSTOM2,UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT)
//EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndWiFiMobileLinkOK_Button_Disconnect_TakePIC)
//EVENT_ITEM(NVTEVT_KEY_DEL,UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndWiFiMobileLinkOK_Tab_REC)
//EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiMobileLinkOK_Button_REC_RAWEN)

EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Button_WIFI_EXIT(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		return NVTEVT_CONSUME;
	}
#endif
//#NT#2016/05/31#Ben Wang -end
#if (WIFI_FUNC == ENABLE)
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	//notify current connected socket,new connect not get IP and socket not create
	//cannot disconnet immediate,suggest after 500 ms
	WIFI_LINKOK_Gsensor_Rec = FALSE;
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
	//delay 500 ms,and then close window
	//in window,use GxTimer replace Timer Delay,it would occupat UI task
	GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DELAY_CLOSE_TIMER, ONE_SHOT);
#else

	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
	//should close network application,then stop wifi
	Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);

    #endif
    #endif

	//must stop rec before close wifi , it will cause hang    van.160907
	FlowWiFiMovie_StopRec();
	Delay_DelayMs(500);

	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
	{
	   	debug_err(("++++++++++++++++++++++++++++++++\r\n"));
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_Button_REC_RAWEN(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;
	UINT32 curStatus = 0;
	curStatus = WiFiCmd_GetStatus();
    uiKeyAct = paramArray[0];
    switch (uiKeyAct)
    {
      case NVTEVT_KEY_PRESS:

        if(curStatus == WIFI_MOV_ST_RECORD)
        {
			if (SysGetFlag(FL_MOVIE_PIM) == MOVIE_PIM_ON) {
				Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 0);
               // UISound_Play(DEMOSOUND_SOUND_SHUTTER_TONE);
			}
		}
    }
	return NVTEVT_CONSUME;
}
INT32  UIMenuWndWiFiMobileLinkOK_Tab_REC(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 result = WIFIAPP_RET_OK;
	UINT32 curStatus = 0;
    UINT32 uiKeyAct;

    uiKeyAct = paramArray[0];
  switch(uiKeyAct)
    {
     case NVTEVT_KEY_PRESS:

        if(System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
        return NVTEVT_CONSUME;

		if (!GxStrg_GetDeviceCtrl(0, CARD_INSERT)) // card insert
		{
            UISound_Play(DEMOSOUND_SOUND_CHECK_CARD_TONE);
			Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD,FLOWWRNMSG_TIMER_2SEC);
			return NVTEVT_CONSUME;
		}

	curStatus = WiFiCmd_GetStatus();

	if (curStatus == WIFI_MOV_ST_LVIEW) {
		if (curStatus == WIFI_MOV_ST_LVIEW) {
			UINT32 MaxTime = MovieExe_GetFreeRecSec();
			if ((MaxTime <= 3) && (SysGetFlag(FL_MOVIE_CYCLIC_REC) == MOVIE_CYCLICREC_OFF)) {
				UISound_Play(DEMOSOUND_SOUND_CARD_FULL_TONE);
				result = WIFIAPP_RET_STORAGE_FULL;
			} else {
				// Reset Current record time
				FlowMovie_SetRecCurrTime(0);

				//#NT#2016/12/30#Isiah Chang -begin
				// Send socket to notify APP movie recording is started.
 				{
 					WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STARTED);
                    UISound_Play(DEMOSOUND_SOUND_REC_TONE);
					FlowWiFiMovie_StartRec();
				}
				//#NT#2016/12/30#Isiah Chang -end
			}
		} else if (curStatus == WIFI_MOV_ST_IDLE) {
			result = WIFIAPP_RET_FAIL;
		}
	} else { //stop rec
    	#if 1
		UINT32 recordTime = FlowMovie_GetRecCurrTime();
        #else
        UINT32 recordTime = 1;
        #endif
		if ((curStatus == WIFI_MOV_ST_RECORD) && ((recordTime >= 1) || (SysGetFlag(FL_MOVIE_TIMELAPSE_REC) != MOVIE_TIMELAPSEREC_OFF))) {
			WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STOPPED);
				UISound_Play(DEMOSOUND_SOUND_STOP_TONE);
            FlowWiFiMovie_StopRec();
            LED_BLUE_TurnOn();
            UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,0);
			FlowMovieWifi_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
			// Notify Maximum Record Time
			UI_SetData(FL_WIFI_MOVIE_MAXRECTIME, MovieExe_GetMaxRecSec());
		} else if ((curStatus == WIFI_MOV_ST_RECORD) && (recordTime < 1)) {
			result = WIFIAPP_RET_FAIL;

		} else if (curStatus == WIFI_MOV_ST_IDLE) {
			result = WIFIAPP_RET_FAIL;

		}
	}
	break;
  	}
//#NT#2016/05/31#Ben Wang -end
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    #if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		return NVTEVT_CONSUME;
	}
#endif
//#NT#2016/05/31#Ben Wang -end
#if (WIFI_FUNC == ENABLE)
#if 0// !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	//notify current connected socket,new connect not get IP and socket not create
	//cannot disconnet immediate,suggest after 500 ms
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
	//delay 500 ms,and then close window
	//in window,use GxTimer replace Timer Delay,it would occupat UI task
	GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DELAY_CLOSE_TIMER, ONE_SHOT);
#else
                  //  UI_SetData(FL_WIFI_LINK,WIFI_LINK_DISCONNECTING);
                  //  Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP,0);
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
	//should close network application,then stop wifi
	Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);

    UISound_Play(DEMOSOUND_SOUND_WIFI_OFF_TONE);//LIU

#endif
	//must stop rec before close wifi , it will cause hang    van.160907
	FlowWiFiMovie_StopRec();
	Delay_DelayMs(500);

	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
	{
	   	debug_err(("++++++++++++++++++++++++++++++++\r\n"));
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}

#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_TakePIC(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
        return NVTEVT_CONSUME;

    }


//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
EVENT_END

//---------------------UIFlowWndMovie_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_END

//----------------------UIFlowWndMovie_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
EVENT_END
EVENT_BEGIN(UIMenuWndWiFiModuleLinkOK_Status_LOCK)//UIMenuWndWiFiModuleLink_Status_LOCK
EVENT_END
//----------------------UIFlowWndMovie_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_time)
EVENT_END

EVENT_BEGIN(UIMenuWndWiFiModuleLinkOK_StaticIcon_PIMC)
EVENT_END

//----------------------UIFlowWndMovie_Static_maxtimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
EVENT_END

//----------------------UIFlowWndMovie_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLinkOK_YMD_Static)
EVENT_END

//----------------------UIFlowWndMovie_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLinkOK_HMS_Static)
EVENT_END
