#include <stdio.h>
#include "UIFlow.h"

// --------------------------------------------------------------------------
// OPTIONS
// --------------------------------------------------------------------------
// MOVIE_SIZE_TAG
// Movie Size Options
TMDEF_BEGIN_OPTIONS(MOVIE_SIZE)
#if (WIFI_FINALCAM_APP_STYLE == DISABLE)
//#NT#2016/08/12#Hideo Lin -begin
//#NT#For small size clone movie
#if (SMALL_CLONE_MOVIE == DISABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)  /// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_NOT_SUPPORT)  /// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)  /// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)  /// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)  /// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_NOT_SUPPORT)  /// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)  /// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)  /// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_NOT_SUPPORT)  /// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)  /// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_NOT_SUPPORT)       /// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_ENABLE)       /// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_NOT_SUPPORT)  /// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_ENABLE)       /// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_ENABLE)       /// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_ENABLE)       /// HD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_NOT_SUPPORT)  /// WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)       /// VGA P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_NOT_SUPPORT)       /// VGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)  /// QVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_NOT_SUPPORT)  /// FHD FHD
#else
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)  /// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_NOT_SUPPORT)  /// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)  /// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)  /// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)  /// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_NOT_SUPPORT)  /// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)  /// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)  /// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_NOT_SUPPORT)  /// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)  /// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_NOT_SUPPORT)  /// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_NOT_SUPPORT)  /// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_NOT_SUPPORT)  /// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_NOT_SUPPORT)  /// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_NOT_SUPPORT)  /// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_NOT_SUPPORT)  /// HD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_NOT_SUPPORT)  /// WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)  /// VGA P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_NOT_SUPPORT)  /// VGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)  /// QVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_NOT_SUPPORT)  /// FHD FHD
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_1920x1080P30, TM_OPTION_NOT_SUPPORT)  /// FHD P30 + FHD  P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30,  TM_OPTION_NOT_SUPPORT)  /// FHD P30 + HD   P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_2560x1440P30_848x480P30,   TM_OPTION_ENABLE)       /// QHD P30 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_2304x1296P30_848x480P30,   TM_OPTION_ENABLE)       /// 3M  P30 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P60_848x480P30,   TM_OPTION_ENABLE)       /// FHD P60 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P60_640x360P30,   TM_OPTION_NOT_SUPPORT)  /// FHD P60 + VGA  P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_848x480P30,   TM_OPTION_ENABLE)       /// FHD P30 + WVGA P30
#endif
//#NT#2016/08/12#Hideo Lin -end
#else
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)  /// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_NOT_SUPPORT)  /// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)  /// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)  /// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)  /// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_NOT_SUPPORT)  /// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)  /// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)  /// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_NOT_SUPPORT)  /// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)  /// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_NOT_SUPPORT)  /// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_ENABLE)       /// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_NOT_SUPPORT)  /// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_NOT_SUPPORT)  /// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_NOT_SUPPORT)  /// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_ENABLE)       /// HD P30
//TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_ENABLE)       /// WVGA P30
//TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)  /// VGA P240
//TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_NOT_SUPPORT)       /// VGA P30
//TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)  /// QVGA P30
//TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_NOT_SUPPORT)  /// FHD FHD
#endif
TMDEF_END_OPTIONS()
// Language Options
TMDEF_BEGIN_OPTIONS(LANGUAGE)
    TMDEF_OPTION_TEXT(LANG_EN)
    TMDEF_OPTION_TEXT(LANG_FR)
    TMDEF_OPTION_TEXT(LANG_ES)
    TMDEF_OPTION_TEXT(LANG_PO)
    TMDEF_OPTION_TEXT(LANG_DE)
    TMDEF_OPTION_TEXT(LANG_IT)
    TMDEF_OPTION_TEXT(LANG_SC)
    TMDEF_OPTION_TEXT(LANG_TC)
    TMDEF_OPTION_TEXT(LANG_RU)
    TMDEF_OPTION_TEXT(LANG_JP)
TMDEF_END_OPTIONS()
// Cyclic recroding Options
TMDEF_BEGIN_OPTIONS(MOVIE_CYCLIC_REC)
    TMDEF_OPTION_TEXT(MOVIE_CYCLIC_REC_OFF)
    TMDEF_OPTION_TEXT(MOVIE_CYCLIC_REC_1MIN)
    TMDEF_OPTION_TEXT(MOVIE_CYCLIC_REC_3MIN)
    TMDEF_OPTION_TEXT(MOVIE_CYCLIC_REC_5MIN)
    //TMDEF_OPTION_TEXT(MOVIE_CYCLIC_REC_10MIN)
TMDEF_END_OPTIONS()
// TV Mode Options
TMDEF_BEGIN_OPTIONS(TV_MODE)
    TMDEF_OPTION_TEXT(TV_NTSC)
    TMDEF_OPTION_TEXT(TV_PAL)
TMDEF_END_OPTIONS()
// Beep Options
TMDEF_BEGIN_OPTIONS(BEEP)
    TMDEF_OPTION_TEXT(BEEP_OFF)
    TMDEF_OPTION_TEXT(BEEP_ON)
TMDEF_END_OPTIONS()


// Frequency Options
TMDEF_BEGIN_OPTIONS(FREQUENCY)
    TMDEF_OPTION_TEXT(50HZ)
    TMDEF_OPTION_TEXT(60HZ)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_MOTION_DET)
    TMDEF_OPTION_TEXT(MOVIE_MOTION_DET_OFF)
    TMDEF_OPTION_TEXT(MOVIE_MOTION_DET_ON)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_HDR)
    TMDEF_OPTION_TEXT(MOVIE_HDR_OFF)
    TMDEF_OPTION_TEXT(MOVIE_HDR_ON)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_AUDIO)
    TMDEF_OPTION_TEXT(MOVIE_AUDIO_OFF)
    TMDEF_OPTION_TEXT(MOVIE_AUDIO_ON)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DATEIMPRINT)
    TMDEF_OPTION_TEXT(MOVIE_DATEIMPRINT_OFF)
    TMDEF_OPTION_TEXT(MOVIE_DATEIMPRINT_ON)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_LDWS)
    TMDEF_OPTION_TEXT_S(MOVIE_LDWS_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_LDWS_ON,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_FCW)
    TMDEF_OPTION_TEXT_S(MOVIE_FCW_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_FCW_ON,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DDD)
    TMDEF_OPTION_TEXT_S(MOVIE_DDD_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_DDD_ON,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_ADAS_CAL)
    TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_OFF,TM_OPTION_ENABLE)
    TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_ON,TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()
// Wi-Fi
TMDEF_BEGIN_OPTIONS(WIFI)
    TMDEF_OPTION_TEXT(WIFI_OFF)
    TMDEF_OPTION_TEXT(WIFI_ON)
TMDEF_END_OPTIONS()
//===============================================
TMDEF_BEGIN_OPTIONS(GSENSOR)
    TMDEF_OPTION_TEXT(GSENSOR_OFF)
    TMDEF_OPTION_TEXT(GSENSOR_LOW)
    TMDEF_OPTION_TEXT(GSENSOR_MED)
    TMDEF_OPTION_TEXT(GSENSOR_HIGH)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(PARKING_MONITONING)
    TMDEF_OPTION_TEXT(PARKING_MONITONING_OFF)
    TMDEF_OPTION_TEXT(PARKING_MONITONING_LOW)
    TMDEF_OPTION_TEXT(PARKING_MONITONING_MED)
    TMDEF_OPTION_TEXT(PARKING_MONITONING_HIGH)
TMDEF_END_OPTIONS()

static int MenuCustom_DateTime(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupDateTimeCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Format(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupFormatCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Default(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupDefaultSettingCtrl, 0);
    return TMF_PROCESSED;
}

static int MenuCustom_Version(UINT32 uiMessage, UINT32 uiParam)
{
    Ux_OpenWindow(&UIMenuWndSetupVersionCtrl, 0);
    return TMF_PROCESSED;
}
BOOL autoWifi_palyback = FALSE;
static int MenuCustom_pb(UINT32 uiMessage, UINT32 uiParam)////2016playback
{
    if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_OK)
    {
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
        UI_SetData(FL_WIFI_LINK,WIFI_LINK_NG);
        Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP,0);
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
        Ux_CloseWindow(&UIFlowWndMovieCtrl, 0);
       autoWifi_palyback = TRUE;
        // Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_PLAYBACK_MODE,0);
    }else{
            Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
            Ux_CloseWindow(&UIFlowWndMovieCtrl, 0);
            autoWifi_palyback = FALSE;
        }
    return TMF_PROCESSED;
}
// --------------------------------------------------------------------------
// ITEMS
// --------------------------------------------------------------------------
// Movie Menu Items
TMDEF_BEGIN_ITEMS(MOVIE)
    TMDEF_ITEM_TEXTID(WIFI)
    TMDEF_ITEM_CUSTOM(MOVIE_PLAYBACK,MenuCustom_pb)//2016playback
    TMDEF_ITEM_CUSTOM(DATE_TIME, MenuCustom_DateTime)
    TMDEF_ITEM_TEXTID(MOVIE_SIZE)
    TMDEF_ITEM_TEXTID(MOVIE_CYCLIC_REC)
#if (SHDR_FUNC == ENABLE)
    TMDEF_ITEM_TEXTID(MOVIE_HDR)
#endif
    //TMDEF_ITEM_TEXTID(MOVIE_EV)
    //TMDEF_ITEM_TEXTID(EV)
    //TMDEF_ITEM_TEXTID(MOVIE_MOTION_DET)
    TMDEF_ITEM_TEXTID(LANGUAGE)
    TMDEF_ITEM_TEXTID(MOVIE_AUDIO)
	TMDEF_ITEM_TEXTID(GSENSOR)
	TMDEF_ITEM_TEXTID(PARKING_MONITONING)
    TMDEF_ITEM_TEXTID(MOVIE_DATEIMPRINT)
    TMDEF_ITEM_TEXTID(BEEP)
    TMDEF_ITEM_TEXTID(FREQUENCY)
    TMDEF_ITEM_TEXTID(TV_MODE)
    TMDEF_ITEM_CUSTOM(FORMAT, MenuCustom_Format)
    TMDEF_ITEM_CUSTOM(DEFAULT, MenuCustom_Default)
    TMDEF_ITEM_CUSTOM(VERSION, MenuCustom_Version)
    #if 0 // To do: need ADAS related ICONs.
    TMDEF_ITEM_TEXTID(MOVIE_LDWS)
    TMDEF_ITEM_TEXTID(MOVIE_FCW)
    TMDEF_ITEM_TEXTID(MOVIE_DDD)
    TMDEF_ITEM_TEXTID(MOVIE_ADAS_CAL)
    #endif
TMDEF_END_ITEMS()

// --------------------------------------------------------------------------
// PAGES
// --------------------------------------------------------------------------
// Movie Menu Pages
TMDEF_BEGIN_PAGES(MOVIE)
    TMDEF_PAGE_TEXT_ICON(MOVIE)
    TMDEF_PAGE_TEXT_ICON(MOVIE) //reserved for setup menu,replace dynamic in MenuCommonItem
TMDEF_END_PAGES()

TMDEF_EMNU(gMovieMenu, MOVIE, Movie_MenuCallback)

// --------------------------------------------------------------------------
// Menu Callback
// --------------------------------------------------------------------------
int Movie_MenuCallback(UINT32 uiMessage, UINT32 uiParam)
{
    UINT16  uwItemId;
    UINT16  uwOption;

    if (uiMessage == TMM_CONFIRM_OPTION)
    {
        uwItemId = LO_WORD(uiParam);
        uwOption = HI_WORD(uiParam);

        switch (uwItemId)
        {
        case IDM_MOVIE_SIZE:
            //Set Movie size event until menu is closed.
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, uwOption);
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_IMAGE_RATIO, 1, GetMovieSizeRatio(UI_GetData(FL_MOVIE_SIZE)));
            break;

        case IDM_EV:
            Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_EV, 1, uwOption);
            break;

        case IDM_MOVIE_HDR:
            //Set Movie HDR event until menu is closed.
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_SHDR, 1, uwOption);
            break;

        case IDM_MOVIE_CYCLIC_REC:
            Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_CYCLIC_REC, 1, uwOption);
            break;

        case IDM_MOVIE_MOTION_DET:
            Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOTION_DET, 1, uwOption);
            break;

        case IDM_MOVIE_AUDIO:
            Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_AUDIO, 1, uwOption);
            break;
        case IDM_BEEP:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_BEEPKEY, 1, uwOption);
            break;

        case IDM_MOVIE_DATEIMPRINT:
            Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_DATE_IMPRINT, 1, uwOption);
            break;
        case IDM_LANGUAGE:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_LANGUAGE, 1, uwOption);
            break;
        case IDM_MOVIE_LDWS:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_LDWS, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
            break;

        case IDM_MOVIE_FCW:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
            //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_FCW, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
            break;
        case IDM_TV_MODE:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_TVFORMAT, 1, uwOption);
            break;

        case IDM_FREQUENCY:
            Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_FREQ, 1, uwOption);
            break;
        case IDM_MOVIE_DDD:
            break;

        case IDM_MOVIE_ADAS_CAL:

            break;
        case IDM_WIFI:
            //Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_WIFI, 1, uwOption);
            if (uwOption ==WIFI_ON)
            {
                if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_NG)
                {
                    if(CheckWiFiMapTbl()!=E_OK)
                    {
                        UI_SetData(FL_WIFI_LINK,WIFI_LINK_NG);
                        return TMF_PROCESSED;
                    }
                    UI_SetData(FL_WIFI_LINK,WIFI_LINK_LINKING);
                    #if(WIFI_UI_FLOW_VER == WIFI_UI_VER_1_0)
                    Ux_OpenWindow(&UIMenuWndWiFiWaitCtrl, 0);
                    #endif
                    BKG_PostEvent(NVTEVT_BKW_WIFI_ON);
                    Ux_CloseWindow(&UIFlowWndMovieCtrl, 0);
                }
            }
            else
            {
                if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_OK)
                {
                    Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                    UI_SetData(FL_WIFI_LINK,WIFI_LINK_NG);
                    Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP,0);
                }

            }
            break;
        default:
            Setup_MenuCallback(uiMessage, uiParam);
            break;
        }
    }

    return TMF_PROCESSED;
}
